### PR TITLE
Fix cheerio w/ new angular-gettext-tools version

### PR DESCRIPTION
**Pull request by pabranch**
gulp-angular-gettext/node_modules/angular-gettext-tools/node_modules/cheerio/lib/cheerio.js:93
_.extend(Cheerio, require('./static'));
  ^
TypeError: undefined is not a function
    at Object.<anonymous> (gulp-angular-gettext/node_modules/angular-gettext-tools/node_modules/cheerio/lib/cheerio.js:93:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (gulp-angular-gettext/node_modules/angular-gettext-tools/node_modules/cheerio/index.js:5:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

### CODE REVIEW

**Comment by gabegorelick** [comment]
`^2.0.1` and `^2.1.2` are in the same semver range, so I'm not sure how this helps.

**Comment by pabranch** [comment]
Hmm, must be local to my environment. With `2.0.1` I get the error in the description. When changed to `2.1.2` (and removing `node_modules/angular-gettext-tools` then `npm install`) it works. It is probably an issue around the new lodash structure.

Ah well, thanks for your time.

**Comment by gabegorelick** [comment]
> removing node_modules/angular-gettext-tools then npm install
This is what's fixing it. When you reinstall your node_modules, it will grab the latest 2.x version.

**Comment by pabranch** [comment]
Thanks, that was exactly it. Rolling the chicken bones before doing the delete distracted me.

**Pull request closed without merging**
