### PR TITLE
Add out compile parameter to support compiling to a single output file

### LINKED ISSUE #13: Compile [out] option
I'm migrating from angular-gettext from grunt to gulp. I can't find a way using this gulp plugin to compile to a single file for every languages `*.po` files.

Here's my grunt configuration that creates a single file `app/scripts/translations.js`

    nggettext_compile: {
      all: {
          options: {
              module: 'ttpApp'
          },
          files: {
              'app/scripts/translations.js': ['po/*.po']
          }
      }
    },

Maybe an [out] option could be implemented, like for extract task ?

### PR DESCRIPTION
**Pull request by Toilal**
Close #13

### CODE REVIEW

**Comment by Toilal** [comment]
For the moment, i didn't use any others gulp plugins (but async as a test dependency). 

Using this implementation ensure that we have the same behavoir between gulp and grunt angular-gettext plugins by using angular-gettext-tools for javascript output.

**Comment by gabegorelick** [comment]
Thanks for the code! I'm not still not convinced I want to add this to gulp-angular-gettext though.

> Using this implementation ensure that we have the same behavoir between gulp and grunt angular-gettext plugins by using angular-gettext-tools for javascript output.

I see no reason that gulp-angular-gettext needs to have the exact same behavior as grunt-angular-gettext. Gulp and Grunt are very different after all. If this were enabling a feature of grunt-angular-gettext that is totally impossible using gulp, that'd be one thing. But if all this does is make it so that you don't have to use a separate gulp plugin to generate your particular JS, then that's another story. There's no way we can support all the possibilities of generated JS that you'd want. But we can output JS that you can then feed into your custom build pipeline.

**Comment by Toilal** [comment]
Ok @gabegorelick no problem, i'll rewrite using the json output only, crafting javascript using gulp.

**Comment by gabegorelick** [comment]
Awesome. Let me know how it goes. It might make sense to add something to the README illustrating how this can be done.

**Pull request closed without merging**
