### PR TITLE
Example extension [.pot]

### PR DESCRIPTION
**Pull request by thiagoalvernaz**
You generate a .pot file and try to build a .po file.

### CODE REVIEW

**Comment by gabegorelick** [comment]
It's correct as written. Compile takes your translations, i.e. PO
files, and converts them to JS/JSON. You definitely don't want to run that
against your template.

**Comment by thiagoalvernaz** [comment]
sorry, send the wrong change, in my project did run code like this:

var gulp = require ('gulp');
var gettext = require ('gulp-angle-gettext);
 
gulp.task ('po', function () {
     return gulp.src (['** / *. html'])
         .pipe (gettext.extract ('template.po' {
             // Options to pass to angular-gettext-tools ...
         }))
         .pipe (gulp.dest ('po /'));
});
 
gulp.task ('translations', function () {
     gulp.src return ('po / ** / *. po')
         .pipe (gettext.compile ({
             // Options to pass to angular-gettext-tools ...
         }))
         .pipe (gulp.dest (dist / translations / '));
});

since when the step command gulp po it creates the file 'template.po' and then the gulp translations command it generates the file template.js

I'm doing something wrong?

**Comment by gabegorelick** [comment]
Not sure I fully understand what the issue is, but it sounds like you might be confused about how gettext works. The `pot` task from the README, which you've renamed to `po` in your posted code, is to generate a PO Template, AKA a POT or .pot file: http://www.icanlocalize.com/site/tutorials/how-to-translate-with-gettext-po-and-pot-files/

You use the POT file to generate a PO file for each locale you want to support. PO files are generated and maintained with 3rd-party tools and services like Transifex, Pootle, Poedit, etc. Once you have your translations in PO files, you can use the `translations` task from the README to convert the PO files into a format usable by angular-gettext, i.e. JSON or JS. 

Here are some more useful links:
http://en.wikipedia.org/wiki/Gettext
https://angular-gettext.rocketeer.be/dev-guide/
https://www.gnu.org/software/gettext/manual/gettext.html

Otherwise, it sounds like everything is working for you. You've generated a POT file with the first task (although you've mislabeled it as a .po file) and the final JS with the second task. If you're still not sure what to do, I recommend reading more about angular-gettext from the official site: https://angular-gettext.rocketeer.be/

**Comment by thiagoalvernaz** [comment]
Thanks, managed to solve my problem.

**Pull request closed without merging**
