### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Toilal**
- [x] Update npm dependencies to latest versions
- [x] Add [editorconfig](http://editorconfig.org/) file
- [x] Fix unit tests
- [x] Implements #13 to support compiling multiple po files to a single js/json file.
- [x] Implements #3 to support relative path for source files when extracting (using `file.relative`)

Maybe you could release `v0.4.0` after merging this one ? (API change with the new out option in compile).

### CODE REVIEW

**Comment by gabegorelick** [comment]
Thanks. I was meaning to do this. I'll take a look at this soon.

**Comment by Toilal** [comment]
@gabegorelick I think it's ready !

**Comment by Toilal** [comment]
@gabegorelick I think it's ready !

**Comment by gabegorelick** [comment]
I pushed v2.0.0, so that should be solved, but what exactly is the use case for concatting the JSON/JS output? Do you have multiple PO files you want to combine?

Also, concatting JSON/JS is kind of orthogonal to this plugin. I only added that feature to extract since a naive concat with something like gulp-concat will generate incorrect PO files.

**Pull request closed without merging**
